export const approvedImageBank: Record<string, string> = {
  lencois: "/manus-storage/ivoei-lencois-maranhenses-editorial_55c4312f.jpg",
  "gramado-canela": "/manus-storage/gramado-canela-editorial_3c42e1d3.jpg",
  "rio-classico": "/manus-storage/rio-classico-editorial_cbed8137.jpg",
  "foz-iguacu": "/manus-storage/foz-iguacu-editorial_57ed991b.jpg",
  "orlando-disney": "/manus-storage/orlando-disney-editorial_2d1b3313.jpg",
  paris: "/manus-storage/paris-editorial_2a844622.jpg",
  "nova-york": "/manus-storage/nova-york-editorial_5d8a44ba.jpg",
  portugal: "/manus-storage/lisboa-porto-editorial_4291f638.jpg",
  miami: "/manus-storage/miami-editorial_9d421109.jpg",
  "buenos-aires": "/manus-storage/buenos-aires-editorial_afe5c9e7.jpg",
  cococay: "/manus-storage/cococay-caribe-editorial_09d6e510.jpg",
  maldivas: "/manus-storage/maldivas-editorial_ff686270.jpg",
  veneza: "/manus-storage/veneza-editorial_72ff9202.jpg",
  "bora-bora": "/manus-storage/bora-bora-editorial_6e86b25b.jpg",
  "tokyo-gastro": "/manus-storage/toquio-editorial_76988a42.jpg",
  universal: "/manus-storage/universal-orlando-editorial_e126d456.jpg",
  mediterraneo: "/manus-storage/mediterraneo-editorial_8e3ec292.jpg",
  alasca: "/manus-storage/alasca-editorial_dba01e92.jpg",
  noruega: "/manus-storage/noruega-editorial_086edd7b.jpg",
  bahamas: "/manus-storage/bahamas-cruzeiro-editorial_c9c187d9.jpg",
  danubio: "/manus-storage/danubio-editorial_948f9a23.jpg",
  "maceio-maragogi": "/manus-storage/maceio-maragogi-editorial_a625e0ec.jpg",
  trancoso: "/manus-storage/porto-seguro-trancoso-editorial_4cbaa74b.jpg",
  "natal-pipa": "/manus-storage/natal-pipa-editorial_c6c49a2f.jpg",
  jeri: "/manus-storage/fortaleza-jeri-editorial_9078e900.jpg",
  florianopolis: "/manus-storage/florianopolis-editorial_2589f21c.jpg",
  "campos-festival": "/manus-storage/ivoei-campos-festival_d8c71d15.jpg",
  laponia: "/manus-storage/ivoei-laponia-aurora_ce604f1d.jpg",
  canastra: "/manus-storage/ivoei-canastra_b5c32b6d.jpg",
  "mendoza-romance": "/manus-storage/ivoei-mendoza-romance_5a17cf55.jpg",
  toscana: "/manus-storage/ivoei-toscana_14773a11.jpg",
  "santorini-romance": "/manus-storage/ivoei-santorini-romance-editorial_666efc9b.jpg",
  sapucai: "/manus-storage/sapucai-editorial_54cbac55.jpg",
  "veneza-carnaval": "/manus-storage/veneza-carnaval-editorial_f6364db4.jpg",
  india: "/manus-storage/taj-mahal-amanhecer-editorial_4bc5eadc.jpg",
  turquia: "/manus-storage/capadocia-baloes-editorial_a493bded.jpg",
  halong: "/manus-storage/halong-bay-cruzeiro-editorial_7b5c0153.jpg",
  minas: "/manus-storage/section11-minas.jpg_0892f971.png",
  "salvador-gastro": "/manus-storage/section11-salvador.jpg_fb88c763.png",
  "serra-gaucha-gastro": "/manus-storage/section11-serra.jpg_7eb86a87.png",
  sawgrass: "/manus-storage/section12-sawgrass_8f7a372e.png",
  "ny-black-friday": "/manus-storage/section12-new-york_fe6c9ef8.png",
  milao: "/manus-storage/section12-milao_d772382b.png",
  panama: "/manus-storage/section12-panama_82d90ada.png",
  "dubai-shopping": "/manus-storage/section12-dubai_4e727cf9.png",
  "ciudad-este": "/manus-storage/section12-ciudad-este_0c8e1317.png",
  milagres: "/manus-storage/section08-milagres_ce8e3146.png",
  "monte-verde": "/manus-storage/section08-monte-verde_34f0f9df.png",
  "noronha-romance": "/manus-storage/section08-noronha_9611b6bc.png",
  vinhedos: "/manus-storage/section08-vinhedos_44e34026.png",
  "jeri-romance": "/manus-storage/section08-jeri_b59ce351.png",
  petropolis: "/manus-storage/section08-petropolis_6cfc0f84.png",
};

const activeStorageImageIds = new Set(["campos-festival", "laponia", "canastra", "mendoza-romance", "toscana"]);

export function imageForOffer(id: string, fallback: string): string {
  return activeStorageImageIds.has(id) ? approvedImageBank[id] : fallback;
}
